* Card Idle
Project description
* Version history
* Story
I don't think there is much room nor need for story in this game, but the
general gist is that you get a single card from a really underground TCG from a
friend, and you start buying more and more cards until you have obscene amounts
of them. I guess? I'd say there's room for improvement here.
* Story Progression
* Gameplay
** Goal
Make numbers go up. What numbers? All of them! Collect more, better, rarer
cards, upgrade cards, increase your hand size, and open boosters faster and faster.
** Game Mechanics
*** Base components
+ The booster pack
  Opening a booster pack rewards the player with some amount of cards randomly
  selected from all unlocked cards. Rarer cards are a lot rarer than more common
  ones. For example, the most basic card has a drop rate of let's say 60%, and
  the second most common card perhaps 30%. With a few hundred cards, the chance
  to drop a really rare one might be astronomically low. Say, 1e-50% chance. To
  get this card, the player would have to increase their drop rates for rarer
  cards, increase how many packs they open per second, and how many cards are in
  each pack. These values are all increased in different ways, and might even
  require doing multiple things, such as procuring more booster packs, getting a way to
  automatically open packs, and increasing how fast and how many are opened at a
  time.
+ Card storage
  The card storage is similar to a bestiary. It shows a long list of all the
  cards that the player owns, and a little number next to them for how many they
  own. Cards can either be in storage or held. If all copies of a card are
  currently held, the icon is greyed out in the storage. If only some are held,
  the number of cards represents how many are in storage as well as how many are
  owned total.
+ The Hand
  The Hand is where the game happens. The player can chose cards from their
  storage to hold, and when held cards have some effect, such as giving the
  player some booster packs each turn, multiplying packs gained by other cards, or
  increasing the action rate of active cards. The hand size - the amount of
  cards that can be held at once - is limited, but can be increased through rare
  cards.
  The cards are activated in the order that they are positioned in the hand.
  For example, having "Increase hand size by 1" before "Set hand size to 5"
  would result in a hand size of 5, not 6.
  When the player adds a card to The Hand, they drag and drop the card into
  place. They can drop the card before or after any other card or, if The Hand
  is empty, into The Hand. A display on the side tells the player how many cards
  they are holding, and their hand size.
*** Upgrading cards
When the player has amassed a certain amount of some card, they can upgrade the
card into a rarer version. This removes the basic card from the game, giving the
player one of the rarer card, and enabling that card to drop. This increases the
number on the card by some formula set on a card-by-card basis. For example, if
the player collect say 100 of the most basic "Income" card, it'll turn into an
upgraded version that produces say 100 booster packs per turn instead of the
original 1. This might not always be worth doing, especially if the player
desires to have multiple copies of a card and they're not sure that they could
procure another copy of the rarer card.
*** Card effects
Every card has some effect, grouped into three categories: Active, Passive, and
Meta.
+ Active cards have some trigger, and some effect that happens when they are
  triggered. For example, "Income" reads "Generates 1 booster pack per turn".
+ Passive cards don't do anything on their own, but rather affect Active cards
  in some way, usually upgrading them. For example, "Potency" reads "Increase
  the number on the next card by 1".
+ Meta cards affect the game in some way, rather than a resource or other cards.
  For example, "Multitasking" reads "Set hand size to 5".
*** Turns
Some active cards activate every turn. By the start of the game, a turn lasts
one second, and the next turn will automatically start at the end of the second.
The player can press a button to end the turn, causing the next turn to happen
sooner. Everything happens at once at the start of a turn, after which nothing
at all happens, so ending your turn is always beneficial.
** Items & Upgrades
*** The cards
See own document
** Progression & Challenge
*** The early game
You start out with only the card =Income= at the lowest level, generating 1
booster pack per turn. You put it in your hand, and then spam the "Next turn"
button a few times until you can afford your first booster pack. What happens
next depends on what card dropped. Most likely, it'll be useful for the player.
For example, it can be a =Potency=, which would increase the amount generated by
=Income= by 1, doubling booster pack generation. Perhaps it's =Echo=, which
would also double pack generation, but by activating =Income= an extra time. We
could also just get another =Income=, which would *also* double our pack
generation if we hold both. Eventually, we might get =Concentration= and
=Conjuring=, our fist dabble in magic! This would allow us to get a little spike
in pack generation early on, and if we were to hold an =Echo= in front of each
one, we'd get four times the parks we otherwise would. With a =Potency= in front
of an =Echo=, it would activate the card two times extra. The player continues
this way, collecting more and more cards to improve their booster pack generation,
clicking to end their turn if they want to, or just leaving the tab open in the
background. Eventually, they'll have gotten enough =Income= cards to upgrade
them, and probably has some fairly interesting generation setup in their hand.
*** Core gameplay loop
Get booster packs
Open them for cards
Upgrade cards
Change setup in The Hand
Watch numbers go up
* Art Style
Whatever I can manage, for starters. The cards will have proc-generated art on
them until further ado, card borders will likely be pixelart by me (so not
terribly good). If the game is ever published, looking for an artist is the top
priority. Realm Grinder has shown us how big a difference a good (not too
overbearing) visual style can make.
* Music & Sounds
Since this game is to be open in the background constantly, any music would be
annoying and the player would quickly mute it. Some cool sound effects, such as
for opening a rare card, is worth considering.
* Technical description
** Libraries
+ Patashu's "Break Eternity" library for *huge* numbers
+ EaselJS for graphics and interaction logic
** Hand card order
The held cards are executed in the order they appear in The Hand. Every tick,
the list of cards in the hand is executed in order, and each passive card is
added to a list of modifiers (in the order they were found). When an active card
is executed it sends it's information though the list of modifying cards,
allowing them to make their changes to the action, before executing the
function.
** The card
Each card consists of a set of paradigms, a name, an image, a set of numbers, a
rarity, and a drop chance. We define these in a JSON file. The paradigms are
defined by functions, and come in groups. These groups are:
+ Trigger
  Determines when the card's action is performed
+ Resource
  Interacts with a resource in some way
+ Operation
  Some mathematical operation
+ Target
  Some other card, subject to this card's action
+ Constraint
  Some limit to the card's function
Adding a new group means adding cards that are fundamentally different from all
previous cards, and as such these groups represent the width of the content,
whereas the individual cards are the depth.
** The turn
At the beginning of each turn, all active cards are executed in the order they
appear. Each card then goes through it's list of modifiers, changing its values
and behaviour accordingly, and then decides based on its constraints and
triggers if it should perform its action or not. If it consumes some resource,
it is consumed before checking the trigger if the trigger is based on the
resource, and afterwards otherwise.

Passive and Meta cards are evaluated when added to The Hand.
* Marketing & Funding
** Demographics
Mostly young men, I'd assume, about my age. Anyone who plays incremental games,
and probably a subset of them that are somewhat familiar with TCGs.
** Platforms & Monetising
The game is web-based, written in JavaScript, so it runs in browsers and nowhere
else. The game will not support phones. Ads might be worth looking into, but I
dislike them, so donations / Patreon is a more likely venture for monetising.
This is not a high priority. This is a hobby project, and there is likely no
money in it. I can maybe expect a few dollars a month tops if people really like
the game and I set up a Patreon.
** Localisation
If anyone volunteers? I doubt there is a single incremental game out there with
localisation, except Realm Grinder I suppose, but they're like corporate level.
It's insane.
* Other Ideas
